security jwt 설정, swagger authentication 설정
Join-Famila/Famila_Server pull request #2
Opened 2023-12-04 08:59 UTC by yeo-chi

spring security JWT 설정하였습니다.

IUWT? 방식으로 refreshToken을 사용하지 않고, accessToken과 UUID값을 사용하도록 하였습니다.

JWT SECRET KEY값은 https://www.javainuse.com/jwtgenerator 에서 알고리즘을 H512로 설정후 Create JWT 버튼을 누르면 자동으로 만들어집니다~

2023-12-04 09:17 UTC, SheepEatLion requested changes

2023-12-04 09:17 UTC, SheepEatLion commented on src/main/resources/application.yml
> +  expiration-second: 1800
jjwt 만료 기간 단위가 밀리세컨드로 알고 있는데 일부러 이렇게 받으신 건가요?! 실제 이 시간뒤에 만료 되는지 테스트 된걸까요?!

2023-12-04 09:17 UTC, SheepEatLion commented on src/main/resources/application.yml
> +  issuer: admin
이슈어도 숨기는 건 어떨까요? 제가 변수로 지정해두면 보안상 더 낫지 않을까 궁금합니다

2023-12-04 09:17 UTC, SheepEatLion commented on src/main/kotlin/join/famila/configuration/security/SecurityConfiguration.kt
> +}
cors 관련 설정이 안들어간 것 같은데 추후에 하실려고 빼두신 건가요?!

2023-12-04 09:26 UTC, sshworld reviewed
😎

2023-12-04 09:26 UTC, sshworld commented on src/main/kotlin/join/famila/configuration/jwt/JwtAuthenticationFilter.kt
> +    private val IDENTIFY: String = "identify"
클래스 내부에서 선언하는 것 보단 companion object로 선언해서 네이밍을 조금 더 구체적으로 바꾼 뒤 static 하게 사용하는 것은 어떨까요?

추가적으로 string 값을 지정하는 거라면 변수타입을 굳이 안보여줘도 괜찮다고 봅니다!

2023-12-04 09:26 UTC, sshworld commented on src/main/kotlin/join/famila/configuration/jwt/JwtAuthenticationFilter.kt
> +        val user = parseIdentificationInformation(token, identify)
getCookieValueByKey 보단 해당 부분이 둘 다 string 이다 보니 named parameter를 사용하기에 적절한 것 같아 보입니다!

2023-12-04 09:26 UTC, sshworld commented on src/main/kotlin/join/famila/configuration/jwt/JwtAuthenticationFilter.kt
> +        val identify = getCookieValueByKey(cookies = request.cookies, key = IDENTIFY)
get 보단 associateCookie~ 가 함수 명으로 조금 더 어울려보여요!

2023-12-04 09:26 UTC, sshworld commented on src/main/kotlin/join/famila/configuration/jwt/TokenProvider.kt
> +        "${user.id}:$USER"
이건 한줄로 표현해도 좋을 것 같아요

2023-12-04 09:26 UTC, sshworld commented on src/main/kotlin/join/famila/configuration/jwt/JwtAuthenticationFilter.kt
> +        return cookies.associate { it.name to it.value }[key] ?: ""
null 일 때 빈 string을 보내는 이유가 뭔가요??

2023-12-04 09:54 UTC, yeo-chi commented on src/main/resources/application.yml
> +  expiration-second: 1800
토큰만드는 코드에서 시간을 초단위로 추가했습니다!

.expiration(from(Instant.now().plusSeconds(expirationSecond)))

2023-12-04 09:54 UTC, yeo-chi commented on src/main/resources/application.yml
> +  issuer: admin
보안상 좋은점이 어떤 것이 있을까요?!

2023-12-04 09:54 UTC, yeo-chi commented on src/main/kotlin/join/famila/configuration/security/SecurityConfiguration.kt
> +}
cors! 설정 추가해야 합니다 ㅋㅋ
클라이언트쪽 서버 정보를 알 수 있을까요?

2023-12-04 09:54 UTC, yeo-chi commented on src/main/kotlin/join/famila/configuration/jwt/JwtAuthenticationFilter.kt
> +        return cookies.associate { it.name to it.value }[key] ?: ""
뒷 로직에 맡기려고헀던 것 같아요! throw 처리 하겠습니다!

2023-12-04 09:54 UTC, yeo-chi commented on src/main/kotlin/join/famila/configuration/jwt/JwtAuthenticationFilter.kt
> +        val identify = getCookieValueByKey(cookies = request.cookies, key = IDENTIFY)
map으로 리턴하면 getAssociateCookie가 맞을 것 같은데, 특정 값 하나만 가져오는 메소드여서 getCookie로 적은 것 같습니다.

identify 라는 키 값외에 나중에 다른 값을 보낼지 몰라 key를 받는 메소드로 작성했는데, identify를 고정으로 하고 메소드 명을 getIdentify로 바꾸는것이 더 좋을 것 같은데 어떻게 생각하시나요?

2023-12-04 09:54 UTC, yeo-chi commented on src/main/kotlin/join/famila/configuration/jwt/JwtAuthenticationFilter.kt
> +    private val IDENTIFY: String = "identify"
companion object가 더 좋아보이네요!

2023-12-04 09:54 UTC, yeo-chi commented on src/main/kotlin/join/famila/configuration/jwt/JwtAuthenticationFilter.kt
> +        val user = parseIdentificationInformation(token, identify)
수정하였습니다!

2023-12-04 09:54 UTC, yeo-chi commented on src/main/kotlin/join/famila/configuration/jwt/JwtAuthenticationFilter.kt
> +        val identify = getCookieValueByKey(cookies = request.cookies, key = IDENTIFY)
추가로 identify는 그냥 식별이라는 것 같아서  identifyCode로 변경하였습니다

2023-12-04 10:24 UTC, sshworld commented on src/main/kotlin/join/famila/configuration/jwt/JwtAuthenticationFilter.kt
> +        val identify = getCookieValueByKey(cookies = request.cookies, key = IDENTIFY)
아 저도 잘 못 봤던 것 같네요 쿠키를 따로 빼서 가져오네요.

식별코드로 받는다면 함수명도 getIdentifyCode가 더 어울리긴 하네요!

2023-12-06 07:43 UTC, sshworld reviewed
😃

2023-12-06 07:43 UTC, sshworld commented on src/main/kotlin/join/famila/configuration/jwt/JwtAuthenticationFilter.kt
> +            ?: throw java.lang.NullPointerException()
kotlin 에도 NPE가 있지 않나요?

2023-12-06 08:25 UTC, yeo-chi commented on src/main/kotlin/join/famila/configuration/jwt/JwtAuthenticationFilter.kt
> +            ?: throw java.lang.NullPointerException()
코틀린 것으로 변경했습니다!

2023-12-07 08:14 UTC, sshworld approved these changes
😎

2023-12-07 08:14 UTC, SheepEatLion approved these changes
승인합니다.!

2024-01-04 07:10 UTC, merged