모임 도메인 엔티티 작성
Join-Famila/Famila_Server pull request #3
Opened 2023-11-02 06:52 UTC by yeo-chi

모임 엔티티 작성하였습니다.

우선 이름을 Club으로 했는데, 더 좋은 피드백 주시면 반영하겠습니다.

채팅관련을 검색해보니 채팅은 따로 Mongodb로 관리하고 나머지는 rdb로 설정한다고 해서 우선 채팅 빼고 나머지 하위 도메인을 Club안에 넣었습니다.

처음엔 @CollectionTable과 @ElementCollection 를 사용해서 하위 도메인 엔티티를 만들었는데, 저건 PK 값이 없어서 저장시 모든 리스트를 삭제하고 다시 넣는다고 해서 자주 변경이 일어나는 하위 도메인들은 OneToMany로 작성했습니다.

OneToMany 단방향은 FK문제가 있다고하여 찾아봤는데 양방향으로 설정 후 단방향처럼 사용해야 문제가 없다고해서 양방향처리 했습니다.

Club안에 Schedule 이라는 일정 하위 도메인이 있는데, 여기에 모임 인원들 참가가 있습니다.
여기에 다시 하위 리스트로 memberId를 넣어야하는데 너무 깊어지는게 아닌가 싶습니다. 이 부분 어떻게하면 좋을지 의견 부탁드려요!

회원은 User로 생각하고 Club안에서는 Member로 들어가는게 어떨까 싶어서 넣었는데 이것도 의견 부탁드려요!

2023-11-02 07:24 UTC, sshworld reviewed
😀😀

2023-11-02 07:24 UTC, sshworld commented on src/main/kotlin/join/famila/persistent/entity/club/MemberEntity.kt
> +class MemberEntity(
Member가 아닌 User로 공유 받았었는데 Member로 가는걸까요?

2023-11-02 07:24 UTC, sshworld commented on src/main/kotlin/join/famila/persistent/entity/club/CategoryEntity.kt
> +class CategoryEntity(
Entity는 따로 생략해도 괜찮아 보이긴 합니다!

2023-11-02 07:24 UTC, sshworld commented on src/main/kotlin/join/famila/persistent/entity/club/ClubEntity.kt
> +import jakarta.persistence.*
import * 은 보기에 좋아 보이지 않은 것 같아요!! 한번 code style 설정 부탁 드려요!

2023-11-02 07:24 UTC, sshworld commented on src/main/kotlin/join/famila/persistent/entity/club/ClubEntity.kt
> +    val schedules: List<ScheduleEntity> = listOf(),
post나 pictures, schedules 같은 경우는 한 모임에 들어가는 내용인 것 같아서 one to many 보단 밑에 categories 처럼 ElementCollection 사용하는게 어떨까요?

2023-11-02 07:36 UTC, yeo-chi commented on src/main/kotlin/join/famila/persistent/entity/club/ClubEntity.kt
> +    val schedules: List<ScheduleEntity> = listOf(),
처음에 ElementCollection으로 썼었는데, 그렇게되면 각각의 ID가 없어서 저장 시 전체 컬랙션을 삭제하고 다시 넣는다고 하더라구요! 그래서 OneToMany로 변경했습니다

2023-11-02 07:40 UTC, yeo-chi commented on src/main/kotlin/join/famila/persistent/entity/club/MemberEntity.kt
> +class MemberEntity(
서비스 회원은 User가 맞습니다. 
Club안에서는  모임의 회원이라고 생각해서 Member로 따로 만든뒤 User와 연결 시키려고 했어요
그렇게 하면 가입일 , 나중에  모임별로 닉네임을 다르게 하는등의 각 모임별로 본인의 설정을 따로 관리 할 수 있지않을까 해서요 ㅋㅋ

2023-11-02 07:41 UTC, yeo-chi commented on src/main/kotlin/join/famila/persistent/entity/club/ClubEntity.kt
> +import jakarta.persistence.*
아 이거 수정해야겠네요 ㅋㅋ

2023-11-02 10:01 UTC, SheepEatLion requested changes

2023-11-02 10:01 UTC, SheepEatLion commented on src/main/kotlin/join/famila/persistent/entity/club/Picture.kt
> +    val updatedAt: LocalDateTime? = null,
@LastModifiedDate 가 들어가야할 것 같습니다!

2023-11-02 10:01 UTC, SheepEatLion commented on src/main/kotlin/join/famila/persistent/entity/club/Picture.kt
> +    val createdAt: LocalDateTime = now(),
이것도 어노테이션으로 자동 관리하면 될 것 같아요!

2023-11-03 07:02 UTC, sshworld commented on src/main/kotlin/join/famila/persistent/entity/club/MemberEntity.kt
> +class MemberEntity(
좋은 것 같아요! 애플리케이션을 사용하는 사람은 유저, 모임에 가입되어있는 사람은 멤버로 통일 시키면 될 것 같네요!

2023-11-03 07:18 UTC, sshworld commented on src/main/kotlin/join/famila/persistent/entity/club/ClubEntity.kt
> +    val schedules: List<ScheduleEntity> = listOf(),
https://ugo04.tistory.com/116 를 확인하니 정말 그렇네요

https://code-mania.tistory.com/86 해당 블로그 마지막 부분을 보면 새로운 해결방법도 보이네요

그치만 지속적으로 변경, 삭제될 수 있다고 생각한다면 식별자를 놔두어 one to many로 가져가는게 맞아보입니다!

2023-11-03 07:27 UTC, sshworld reviewed
😎

2023-11-03 07:27 UTC, sshworld commented on src/main/kotlin/join/famila/persistent/entity/club/Member.kt
> +    val deletedAt: LocalDateTime? = null,
한번 탈퇴한 모임은 재가입이 불가능 할까요?

위에 club 도 마찬가지로 soft delete 방법 채택한 이유가 궁금해요!

2023-11-03 07:27 UTC, sshworld commented on src/main/kotlin/join/famila/persistent/entity/club/Schedule.kt
> +    val createdAt: LocalDateTime = now(),
스케줄은 update가 불가능할까요?

2023-11-03 07:27 UTC, sshworld commented on src/main/kotlin/join/famila/persistent/entity/club/Tag.kt
> +    YOGA("요가"),
해당 줄 바꿈 컨벤션을 어떻게 가져가는게 좋을까요?

저는 enum 이어도 한칸씩 띄우면 좋아보여요!

2023-11-03 07:27 UTC, sshworld commented on src/main/kotlin/join/famila/persistent/entity/club/Club.kt
> +class Club(
soft delete를 한다면 Where annotation 사용해주면 좋지 않을까요?!

2023-11-03 07:27 UTC, sshworld commented on src/main/kotlin/join/famila/persistent/entity/club/Post.kt
> +    val content: String,
해당 content도 수정가능성이 보이네요! ㅋㅋ

2023-11-12 01:36 UTC, yeo-chi commented on src/main/kotlin/join/famila/persistent/entity/club/Category.kt
> +@Table
원래 클래스 이름에 접미사로 Entity를 적어서 테이블 어노테이션이 필요했는데, Entity접미사를 지웠으니 이것도 필요 없겠네요!

2023-11-12 01:39 UTC, yeo-chi commented on src/main/kotlin/join/famila/persistent/entity/club/Picture.kt
> +    val createdAt: LocalDateTime = now(),
이것도 @CreatedDate 붙여놓을게요~

2023-11-12 01:50 UTC, yeo-chi commented on src/main/kotlin/join/famila/persistent/entity/club/Member.kt
> +    val deletedAt: LocalDateTime? = null,
이거 생각 못했었어요! 여기서는 soft delete 하면 안되겠네요! 이력을 관리 할 거라면 따로 history 테이블을 만들어야 할 것 같아요

2023-11-12 01:52 UTC, yeo-chi commented on src/main/kotlin/join/famila/persistent/entity/club/Member.kt
> +    val deletedAt: LocalDateTime? = null,
club은 나중에 용품도 판매하는 돈과 관련 될 것 같아 아예 데이터 삭제보단 정보를 계속 가지고 있는 것이 좋을 것 같다고 생각했어요

2023-11-12 12:25 UTC, SheepEatLion approved these changes
수고하셨어요!

2023-11-12 16:08 UTC, merged